In [1]:
import torch
import numpy as np

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: {}\n".format(x))

## Tensor creation

In [4]:
describe(torch.Tensor(2, 3)) # random values
describe(torch.rand(2, 3)) # random uniform
describe(torch.randn(2, 3)) # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0.4169, 0.0431, 0.2059],
        [0.6201, 0.4813, 0.9793]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[-1.0722, -0.8573,  1.1385],
        [ 0.0601,  0.7980, -2.0014]])



Tensor with same scalar

In [5]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5) # _ means inplace
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 1., 1.],
        [1., 1., 1.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[5., 5., 5.],
        [5., 5., 5.]])



Tensor from list

In [6]:
x = torch.Tensor([[1,2,3],
                  [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])



Tensor from numpy

In [8]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy)) # DoubleTensor - np.float64

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0.8442, 0.7876, 0.2372],
        [0.9511, 0.6461, 0.3386]], dtype=torch.float64)



## Tensor types

In [9]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [10]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[1, 2, 3],
        [4, 5, 6]])



In [11]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[1, 2, 3],
        [4, 5, 6]])



In [12]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])



## Tensor Operations

In [3]:
x = torch.randn(2, 3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[-0.4388,  0.4317, -0.1915],
        [ 0.6701,  0.2851,  0.7160]])



In [4]:
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[-0.8776,  0.8634, -0.3829],
        [ 1.3402,  0.5701,  1.4320]])



In [5]:
describe(x + x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[-0.8776,  0.8634, -0.3829],
        [ 1.3402,  0.5701,  1.4320]])



specific rows and cols

In [6]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: tensor([0, 1, 2, 3, 4, 5])



In [7]:
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])



In [9]:
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: tensor([3, 5, 7])



In [10]:
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: tensor([ 3, 12])



In [11]:
describe(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: tensor([[0, 3],
        [1, 4],
        [2, 5]])



## Indexing, Slicing and Joining

In [12]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])



In [15]:
describe(x[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: tensor([[0, 1]])



In [16]:
describe(x[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 1



Complex indexing

In [17]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: tensor([[0, 2],
        [3, 5]])



In [20]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [0, 1, 2]])



In [21]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: tensor([0, 4])



Concatenation

In [22]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])



In [23]:
describe(torch.cat([x,x], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])



In [24]:
describe(torch.cat([x,x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])



In [25]:
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



Linear Algebra

In [29]:
x1 = torch.arange(6).view(2, 3).float()
describe(x1)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: tensor([[0., 1., 2.],
        [3., 4., 5.]])



In [27]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])



In [30]:
describe(torch.mm(x1, x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: tensor([[ 3.,  6.],
        [12., 24.]])



## Tensors and Computational Graphs

In [31]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

True


In [32]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

True


In [33]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 21.0

False


## Cuda Tensors

In [34]:
torch.cuda.is_available()

False

In [35]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [36]:
x = torch.rand(3, 3).to(device)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: tensor([[0.5136, 0.1718, 0.8973],
        [0.6709, 0.6919, 0.3315],
        [0.9563, 0.6015, 0.4960]])



# Exercises

“Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.”

In [38]:
x = torch.rand(3, 3)
print(x)
x.unsqueeze(0)

tensor([[0.6310, 0.8245, 0.7650],
        [0.4616, 0.2545, 0.3766],
        [0.1777, 0.5202, 0.3500]])


tensor([[[0.6310, 0.8245, 0.7650],
         [0.4616, 0.2545, 0.3766],
         [0.1777, 0.5202, 0.3500]]])

“Remove the extra dimension you just added to the previous tensor.”

In [39]:
x.squeeze(0)

tensor([[0.6310, 0.8245, 0.7650],
        [0.4616, 0.2545, 0.3766],
        [0.1777, 0.5202, 0.3500]])

“Create a random tensor of shape 5x3 in the interval [3, 7)”

In [41]:
x = torch.rand(size=(5,3))
3 + x * (7-3)

tensor([[4.8303, 3.9183, 3.3751],
        [3.9411, 6.1944, 3.4616],
        [4.6441, 5.9413, 6.9631],
        [6.1852, 3.6303, 6.9788],
        [4.8870, 3.2496, 4.3859]])

“Create a tensor with values from a normal distribution (mean=0, std=1).”


In [42]:
torch.randn(3,5)

tensor([[-2.2252, -0.4406,  1.5128,  0.0160, -0.6401],
        [-0.7529, -0.7839,  1.2718,  0.5600,  0.0952],
        [ 0.2845,  0.2083, -1.2869,  2.0168, -0.7491]])

“Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).”

In [43]:
x = torch.Tensor([1, 1, 1, 0, 1])
x.nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

“Create a random tensor of size (3,1) and then horizontally stack four copies together.”


In [49]:
x = torch.rand(3,1)
torch.cat([x, x, x, x], dim=1)


tensor([[0.7617, 0.7617, 0.7617, 0.7617],
        [0.1498, 0.1498, 0.1498, 0.1498],
        [0.8513, 0.8513, 0.8513, 0.8513]])

“Return the batch matrix-matrix product of two three-dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).”


In [52]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a,b)

RuntimeError: self must be a matrix

“Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).”

In [64]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
describe(b)
describe(b.unsqueeze(0).expand(a.size(0), *b.size()))
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

Type: torch.FloatTensor
Shape/size: torch.Size([5, 4])
Values: tensor([[0.8945, 0.7840, 0.8510, 0.6987],
        [0.7993, 0.4709, 0.1220, 0.8201],
        [0.6965, 0.8197, 0.2243, 0.2642],
        [0.4757, 0.0184, 0.1811, 0.9534],
        [0.3166, 0.6013, 0.3056, 0.6072]])

Type: torch.FloatTensor
Shape/size: torch.Size([3, 5, 4])
Values: tensor([[[0.8945, 0.7840, 0.8510, 0.6987],
         [0.7993, 0.4709, 0.1220, 0.8201],
         [0.6965, 0.8197, 0.2243, 0.2642],
         [0.4757, 0.0184, 0.1811, 0.9534],
         [0.3166, 0.6013, 0.3056, 0.6072]],

        [[0.8945, 0.7840, 0.8510, 0.6987],
         [0.7993, 0.4709, 0.1220, 0.8201],
         [0.6965, 0.8197, 0.2243, 0.2642],
         [0.4757, 0.0184, 0.1811, 0.9534],
         [0.3166, 0.6013, 0.3056, 0.6072]],

        [[0.8945, 0.7840, 0.8510, 0.6987],
         [0.7993, 0.4709, 0.1220, 0.8201],
         [0.6965, 0.8197, 0.2243, 0.2642],
         [0.4757, 0.0184, 0.1811, 0.9534],
         [0.3166, 0.6013, 0.3056, 0.6072]]])



tensor([[[1.2719, 1.0458, 0.7676, 1.5298],
         [2.0996, 1.7340, 1.2873, 2.1870],
         [1.8259, 1.7028, 1.0867, 1.7878],
         [1.8937, 1.3501, 0.8950, 1.9875]],

        [[1.3478, 1.3201, 0.5614, 1.4819],
         [1.3780, 1.3270, 1.0505, 1.3757],
         [1.2524, 1.1082, 0.8733, 1.3625],
         [1.9184, 1.6279, 1.1819, 2.2725]],

        [[1.1023, 1.0759, 0.5631, 0.9252],
         [1.1477, 0.9825, 0.3330, 1.0769],
         [2.0531, 2.0426, 1.1107, 1.7774],
         [1.7106, 1.5252, 1.2149, 2.0504]]])